"""google oauth, assessments, mistakes, parent access tokens

Hand-written rather than autogenerated: this production schema was
originally created by Prisma, so `alembic revision --autogenerate` also
picks up a large amount of cosmetic drift (TEXT vs VARCHAR, enum types
vs plain strings, Prisma-style index names) between the live tables and
what SQLAlchemy declares. None of that is touched here — this migration
does exactly and only the additive changes the September 2026 feature
work needs: one nullable/unique column and one loosened NOT NULL
constraint on User, plus five new tables. Nothing existing is altered,
renamed, or dropped.

Revision ID: 0001_new_features
Revises:
Create Date: 2026-09-17

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "0001_new_features"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # --- User: Google OAuth support -------------------------------------
    op.add_column("User", sa.Column("googleId", sa.String(), nullable=True))
    op.create_unique_constraint("User_googleId_key", "User", ["googleId"])
    op.alter_column("User", "passwordHash", existing_type=sa.String(), nullable=True)

    # --- Question: topic-scoped question bank ----------------------------
    op.create_table(
        "Question",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("topicId", sa.String(), sa.ForeignKey("Topic.id", ondelete="CASCADE", onupdate="CASCADE"), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("options", sa.JSON(), nullable=False),
        sa.Column("correctIndex", sa.Integer(), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=True),
        sa.Column("createdAt", sa.DateTime(), nullable=False),
    )

    # --- Assessment: one quiz/test/diagnostic attempt ---------------------
    op.create_table(
        "Assessment",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("userId", sa.String(), sa.ForeignKey("User.id", ondelete="CASCADE", onupdate="CASCADE"), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("topicId", sa.String(), sa.ForeignKey("Topic.id", ondelete="SET NULL", onupdate="CASCADE"), nullable=True),
        sa.Column("chapterId", sa.String(), sa.ForeignKey("Chapter.id", ondelete="SET NULL", onupdate="CASCADE"), nullable=True),
        sa.Column("subjectId", sa.String(), sa.ForeignKey("Subject.id", ondelete="SET NULL", onupdate="CASCADE"), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("totalQuestions", sa.Integer(), nullable=False),
        sa.Column("startedAt", sa.DateTime(), nullable=False),
        sa.Column("completedAt", sa.DateTime(), nullable=True),
    )

    # --- AssessmentQuestion: per-question answer within an attempt --------
    op.create_table(
        "AssessmentQuestion",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("assessmentId", sa.String(), sa.ForeignKey("Assessment.id", ondelete="CASCADE", onupdate="CASCADE"), nullable=False),
        sa.Column("questionId", sa.String(), sa.ForeignKey("Question.id", ondelete="CASCADE", onupdate="CASCADE"), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("selectedIndex", sa.Integer(), nullable=True),
        sa.Column("isCorrect", sa.Boolean(), nullable=True),
        sa.Column("answeredAt", sa.DateTime(), nullable=True),
    )

    # --- Mistake: categorized error per wrong answer -----------------------
    op.create_table(
        "Mistake",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("userId", sa.String(), sa.ForeignKey("User.id", ondelete="CASCADE", onupdate="CASCADE"), nullable=False),
        sa.Column("topicId", sa.String(), sa.ForeignKey("Topic.id", ondelete="CASCADE", onupdate="CASCADE"), nullable=False),
        sa.Column("assessmentQuestionId", sa.String(), sa.ForeignKey("AssessmentQuestion.id", ondelete="CASCADE", onupdate="CASCADE"), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("createdAt", sa.DateTime(), nullable=False),
    )

    # --- ParentAccessToken: student-generated read-only share link --------
    op.create_table(
        "ParentAccessToken",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("userId", sa.String(), sa.ForeignKey("User.id", ondelete="CASCADE", onupdate="CASCADE"), nullable=False),
        sa.Column("token", sa.String(), nullable=False, unique=True),
        sa.Column("label", sa.String(), nullable=True),
        sa.Column("createdAt", sa.DateTime(), nullable=False),
        sa.Column("revokedAt", sa.DateTime(), nullable=True),
    )


def downgrade() -> None:
    op.drop_table("ParentAccessToken")
    op.drop_table("Mistake")
    op.drop_table("AssessmentQuestion")
    op.drop_table("Assessment")
    op.drop_table("Question")
    op.alter_column("User", "passwordHash", existing_type=sa.String(), nullable=False)
    op.drop_constraint("User_googleId_key", "User", type_="unique")
    op.drop_column("User", "googleId")
